package co.edu.uniquindio.proyecto.model.enums;

public enum TypeBusiness {
    PANADERIA, OTRO, CAFETERIA, BAR,
    RESTAURANTE, DISCOTECA, SUPERMERCADO, TIENDA,
    HELADERIA,VETERINARIA,ESTACION_SERVICIO,FARMACIA
    ,PIZZERIA,ACADEMIA,AUTO_LAVADO,PARQUEADERO,
    TIENDA_ROPA,FOTOCOPIADO,CONSULTORIO_MEDICO,
    PAPELERIA,SALON_BELLEZA,LAVANDERIA,
    CENTRO_DEPORTIVO
}
